[package]
name = "rp-postgrest"
version = "1.6.0"
authors = [
  "Bobbie Soedirgo <bobbie@soedirgo.dev>",
  "Roberts Pumpurs <roberts@pumpurlabs.com>",
]
description = "PostgREST client-side library"
homepage = "https://github.com/roberts-pumpurs/postgrest-rs"
repository = "https://github.com/roberts-pumpurs/postgrest-rs"
readme = "README.md"
license = "Apache-2.0 OR MIT"
keywords = ["postgres", "postgrest", "rest", "api"]
categories = ["development-tools"]
edition = "2021"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }

[dev-dependencies]
json = "0.12"
tokio = { version = "1", features = ["full"] }
